Repository nextcloud-libraries/nextcloud-auth, pull requests merged in 2022-08, with the labels that each got.

#448 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#408 Bundle improvements
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  CHANGELOG.md
  README.md
  babel.config.js
  lib/index.ts
  lib/requesttoken.ts
  lib/user.ts
  package-lock.json
  package.json
  rollup.config.js
  test/request-token.test.js
  tsconfig.json
Labels: documentation, enhancement, dependencies

#455 Release process
  .github/dependabot.yml
  .github/workflows/doc-publish.yml
  .github/workflows/publish.yml
  CHANGELOG.md
  README.md
  package.json
Labels: enhancement
