Repository nextcloud-libraries/nextcloud-auth, pull requests merged in 2024-07, with the labels that each got.

#664 Add SPDX header
  .github/dependabot.yml
  .github/workflows/block-unconventional-commits.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/documentation.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/node-test.yml
  .github/workflows/npm-publish.yml
  .github/workflows/publish.yml
  .github/workflows/reuse.yml
  .gitignore
  AUTHORS.md
  CHANGELOG.md
  LICENSES/CC0-1.0.txt
  LICENSES/GPL-3.0-or-later.txt
  LICENSES/MIT.txt
  README.md
  REUSE.toml
  lib/index.ts
  lib/requesttoken.ts
  lib/user.ts
  test/request-token.test.ts
  vite.config.ts
  vitest.config.ts
Labels: documentation, 3. to review

#643 docs: Fix link to online docs
  README.md
Labels: 3. to review

#666 feat: add guest nickname handling
  lib/guest.ts
  lib/index.ts
  package-lock.json
  package.json
Labels: enhancement, 3. to review
